version: "2"

volumes:
  postgresql-data:
    driver: local
  rails-data:
    driver: local


services:
  db:
    image: postgres:9.6
    ports:
    - 5433:5432
    volumes:
    - postgresql-data:/var/lib/postgresql/data
    env_file:
    - dev.env
  web:
    image: your_image_name_here:latest
    build:
      context: "."
      dockerfile: dev.Dockerfile
    command: rails server -b 0.0.0.0 -p 3000 -P /tmp/rails.pid
    ports:
    - 3000:3000
    working_dir: "/usr/src/app"
    volumes:
    - ".:/usr/src/app"
    - rails-data:/usr/local/bundle
    stdin_open: true
    tty: true
    links:
    - db
    depends_on:
    - db
    env_file:
    - dev.env
